### ISSUE TITLE
Which issue is referenced is ovh-dedicated-wipe-and-install-nixos.sh?

### ISSUE THREAD

**Issue by casey** [nix-community/nixos-install-scripts#12]
`ovh-dedicated-wipe-and-install-nixos.sh` contains this comment:

```
# OVH has an issue where on newer kernels, it can take up to 20 minutes
# for the default gateway to not be 'linkdown' when booting. See #812.
# We observed that with the 4.15 kernels so far, including OVH's own
# Ubuntu 18.04.
# Our workaround so far is to use the 4.9 kernel.
boot.kernelPackages = pkgs.linuxPackages_4_9;
```

I was curious if this was fixed, but didn't see an issue number 812 in this repository. Where can I find this issue?

Thanks for this repo, it's a huge help! I was able to adapt the OVH install script to a different server type and got everything working.

**Comment by happysalada** [comment]
Just saying that I came to the project after this was written and so unfortunately, I have no knowledge either of what 812 refers to here.
Since kernel 4.9 is 5 years old, this might be completely out of date.
If you ever find out more about this, happy to help you merge updates to the documentation.

**Comment by casey** [comment]
Thanks for the info! I removed that line from my config which installed a 5.10 kernel, and everything was fine, both before and after rebooting.

**Comment by nh2** [comment]
Apologies, `#812` was referring to an issue on my internal issue tracker before open-sourcing `nixos-install-scripts.

The OVH boot delay issue menetioned is fixed with current kernels. I wrote the following internal commit message abou tit:

```
With current NixOS 21.11 kernel Linux 5.10.88, the issue from #812 is gone.

Running

    ethtool --negotiate eno3

or doing 5 subsequent reboots now no longer takes 20 minutes.

Doing this upgrade fixes the deployment error

    iptables v1.8.7 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in chain PREROUTING

caused by current nftables not supporting the old kernel.
```

So those comments can be removed.
